bank/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'bank'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^rachunki/$', views.rachunki, name='rachunki'),
    url(r'^rachunek/(?P<numer>[0-9]+){1}/$', views.rachunek, name='rachunek'),
    url(r'^historia/(?P<numer>[0-9]+){1}/$', views.historia, name='historia'),
    url(r'^zamknij/(?P<numer>[0-9]+){1}/$', views.zamknij, name='zamknij'),
    url(r'^otworz/$', views.otworz, name='otworz'),
    url(r'^kolejny_dzien/$', views.kolejny_dzien, name='kolejny_dzien'),
    url(r'^rodzaj/(?P<id>[0-9]+){1}/$', views.rodzaj, name='rodzaj'),
    url(r'^oferta/$', views.oferta, name='oferta'),
    url(r'^rejestracja/$', views.rejestracja, name='rejestracja'),
]

bd/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('bank.urls')),
]

bank/models.py
from django.db import connection
from decimal import Decimal

class Klient:

    def __init__ (self, data_tuple):
        (id, imie, nazwisko, login, haslo) = data_tuple
        self.id = id
        self.imie = imie
        self.nazwisko = nazwisko
        self.login = login
        self.haslo = haslo

    @staticmethod
    def get_klient_by_login(login):
        data = ()
        with connection.cursor() as cursor:
            cursor.execute("SELECT id, Imie, Nazwisko, Login, Haslo FROM Klient WHERE Login = %s;", [login])
            data = cursor.fetchone()
        return data

    @staticmethod
    def get_klient_by_id(id):
        data = ()
        with connection.cursor() as cursor:
            cursor.execute("SELECT id, Imie, Nazwisko, Login, Haslo FROM Klient WHERE id = %s;", [id])
            data = cursor.fetchone()
        return data

    def registration(self):
        return self.__save()

    def __save(self):
        result = False
        with connection.cursor() as cursor:
            cursor.execute("INSERT INTO Klient (Imie, Nazwisko, Login, Haslo) VALUES (%s, %s, %s, %s);", [self.imie, self.nazwisko, self.login, self.haslo])
            result = True
        return result

    def get_rachunki(self):
        data = []
        with connection.cursor() as cursor:
            cursor.execute("SELECT id, id_Klient, id_Rodzaj, Numer, Saldo, Dni_od_odsetek FROM Rachunek WHERE id_Klient = %s;", [self.id])
            for rachunek_tuple in cursor.fetchall():
                data.append(Rachunek(rachunek_tuple))
        return tuple(data)



class Rodzaj:
    def __init__(self, data_tuple):
        (id, nazwa, odsetki, co_ile_naliczane) = data_tuple
        self.id = id
        self.nazwa = nazwa
        self.odsetki = odsetki
        self.co_ile_naliczane = co_ile_naliczane

    @staticmethod
    def get_rodzaj_by_id(id):
        data = ()
        with connection.cursor() as cursor:
            cursor.execute("SELECT id, Nazwa, Odsetki, Co_ile_naliczane FROM Rodzaj WHERE id = %s;", [id])
            data = cursor.fetchone()
        return data

    @staticmethod
    def get_rodzaj_by_nazwa(nazwa):
        data = ()
        with connection.cursor() as cursor:
            cursor.execute("SELECT id, Nazwa, Odsetki, Co_ile_naliczane FROM Rodzaj WHERE Nazwa = %s;", [nazwa])
            data = cursor.fetchone()
        return data

    @staticmethod
    def get_all_rodzaj():
        data = ()
        with connection.cursor() as cursor:
            cursor.execute("SELECT id, Nazwa, Odsetki, Co_ile_naliczane FROM Rodzaj;")
            data = cursor.fetchall()
        return data


class Rachunek:
    def __init__(self, data_tuple):
        (id, id_klient, id_rodzaj, numer, saldo, dni_od_odsetek) = data_tuple
        self.id = id
        self.klient = Klient(Klient.get_klient_by_id(id_klient))
        self.rodzaj = Rodzaj(Rodzaj.get_rodzaj_by_id(id_rodzaj))
        self.numer = numer
        self.saldo = saldo
        self.dni_od_odsetek = dni_od_odsetek

    def wplata(self, kwota, operacja):
        zmiana = self.saldo
        self.saldo = self.saldo + kwota
        zmiana = self.saldo - zmiana
        return self.__save_saldo(operacja, zmiana)

    def wyplata(self, kwota, operacja):
        zmiana = self.saldo
        self.saldo = max((self.saldo - kwota), 0)
        zmiana = self.saldo - zmiana
        return self.__save_saldo(operacja, zmiana)

    def aktualizacja(self, kwota, operacja):
        zmiana = self.saldo
        self.saldo = max((self.saldo + kwota), 0)
        zmiana = self.saldo - zmiana
        return self.__save_saldo(operacja, zmiana) and self.__save_dni_od_odsetek()

    def __save_saldo(self, operacja, zmiana):
        result = False
        with connection.cursor() as cursor:
            cursor.execute("UPDATE Rachunek SET Saldo = %s WHERE id = %s;", [self.saldo, self.id])
            result = Operacja_wykonana((None , self.id, operacja.id, None, zmiana)).save()
        return result

    def __save_dni_od_odsetek(self,):
        result = False
        with connection.cursor() as cursor:
            cursor.execute("UPDATE Rachunek SET Dni_od_odsetek = 0 WHERE id = %s;", [self.id])
            result = True
        return result

    def get_history(self):
        data = []
        for operacja_wykonana_tuple in Operacja_wykonana.get_operacje_wykonane_by_id_rachunek(self.id):
            data.append(Operacja_wykonana(operacja_wykonana_tuple))
        return tuple(data)

    def close(self):
        result = False
        with connection.cursor() as cursor:
            cursor.execute("SELECT zamknij_rachunek(%s);", [self.id])
            result = True
        return result

    def amount(self):
        return self.saldo * self.rodzaj.odsetki

    @staticmethod
    def get_rachunek_by_numer(numer):
        data = ()
        with connection.cursor() as cursor:
            cursor.execute("SELECT id, id_Klient, id_Rodzaj, Numer, Saldo, Dni_od_odsetek FROM Rachunek WHERE Numer = %s;", [numer])
            data = cursor.fetchone()
        return data

    @staticmethod
    def get_rachunek_by_id(id):
        data = ()
        with connection.cursor() as cursor:
            cursor.execute("SELECT id, id_Klient, id_Rodzaj, Numer, Saldo, Dni_od_odsetek FROM Rachunek WHERE id = %s;", [id])
            data = cursor.fetchone()
        return data

    @staticmethod
    def check_free(numer):
        return not Rachunek.get_rachunek_by_numer(numer)

    @staticmethod
    def otworz_rachunek(id_klient, rodzaj_nazwa, numer):
        rodzaj = Rodzaj(Rodzaj.get_rodzaj_by_nazwa(rodzaj_nazwa))
        result = False
        with connection.cursor() as cursor:
            cursor.execute("SELECT otworz_rachunek(%s, %s, %s);", [id_klient, rodzaj.id, numer])
            result = True
        return result

    @staticmethod
    def next_day():
        result = False
        with connection.cursor() as cursor:
            cursor.execute("SELECT next_day()")
            result = True
        return result

    @staticmethod
    def interest():
        result = False
        with connection.cursor() as cursor:
            cursor.execute("SELECT Rachunek.id, id_Klient, id_Rodzaj, Numer, Saldo, Dni_od_odsetek FROM Rachunek LEFT OUTER JOIN Rodzaj ON Rachunek.id_Rodzaj = Rodzaj.id WHERE Dni_od_odsetek >= Co_ile_naliczane;")
            operacja = Operacja(Operacja.get_operacja_by_nazwa('aktualizacja'))
            result = True
            for rachunek_tuple in cursor.fetchall():
                rachunek = Rachunek(rachunek_tuple)
                result = result and operacja.realize(rachunek, rachunek.amount())
        return result;


class Operacja:

    def __init__(self, data_tuple):
        (id, nazwa) = data_tuple
        self.id = id
        self.nazwa = nazwa

    def realize(self, rachunek, kwota):
        if self.nazwa == 'wplata':
            return rachunek.wplata(Decimal(kwota), self)
        if self.nazwa == 'wyplata':
            return rachunek.wyplata(Decimal(kwota), self)
        if self.nazwa == 'aktualizacja':
            return rachunek.aktualizacja(Decimal(kwota), self)

    @staticmethod
    def get_operacja_by_nazwa(nazwa):
        data = ()
        with connection.cursor() as cursor:
            cursor.execute("SELECT id, Nazwa FROM Operacja WHERE Nazwa = %s;", [nazwa])
            data = cursor.fetchone()
        return data

    @staticmethod
    def get_operacja_by_id(id):
        data = ()
        with connection.cursor() as cursor:
            cursor.execute("SELECT id, Nazwa FROM Operacja WHERE id = %s;", [id])
            data = cursor.fetchone()
        return data

    @staticmethod
    def operacja(rachunek, operacja, kwota):
        operacja_tuple = Operacja.get_operacja_by_nazwa(operacja)
        if operacja_tuple:
            return Operacja(operacja_tuple).realize(rachunek, kwota)
        else:
            return False;


class Operacja_wykonana:

    def __init__(self, data_tuple):
        (id, id_rachunek, id_operacja, data, zmiana) = data_tuple
        self.id = id
        self.rachunek = Rachunek(Rachunek.get_rachunek_by_id(id_rachunek))
        self.operacja = Operacja(Operacja.get_operacja_by_id(id_operacja))
        self.data = data
        self.zmiana = zmiana

    @staticmethod
    def get_operacje_wykonane_by_id_rachunek(id_rachunek):
        data = ()
        with connection.cursor() as cursor:
            cursor.execute("SELECT id, id_Rachunek, id_Operacja, Data, Zmiana FROM Operacja_wykonana WHERE id_Rachunek = %s;", [id_rachunek])
            data = cursor.fetchall()
        return data

    def save(self):
        result = False
        with connection.cursor() as cursor:
            cursor.execute("INSERT INTO Operacja_wykonana (id_Rachunek, id_Operacja, Zmiana) VALUES (%s, %s, %s);", [self.rachunek.id, self.operacja.id, self.zmiana])
            result = True
        return result

class Test:
    
    @staticmethod
    def testowa():
        data = ()
        with connection.cursor() as cursor:
            cursor.execute('''BEGIN; 
                SELECT dupa('cities_cur'); 
                FETCH ALL IN "cities_cur"; COMMIT;''')
            data = cursor.fetchone()
        return data

bank/views.py
from django.shortcuts import render
from .models import Klient, Rachunek, Rodzaj, Operacja, Operacja_wykonana, Test
from django.http import HttpResponseRedirect
from django.template.loader import render_to_string

def login(request):
    if 'login' in request.session:
        return index(request, 'Podales popwarne dane, zostales zalogowany. Witamy!')
    if request.method == 'POST':
        login = request.POST['login']
        haslo = request.POST['haslo']
        data = Klient.get_klient_by_login(login)
        if data and Klient(data).haslo == haslo:
            request.session['login'] = login
            return index(request, 'Podales popwarne dane, zostales zalogowany. Witamy!')
        else:
            return render(request, 'bank/login.html', {'info': 'Bledne dane'})
    else:
        return render(request, 'bank/login.html', {})

def logout(request):
    if 'login' in request.session:
        del request.session['login']
    return HttpResponseRedirect('/login/')

def index(request, main=render_to_string('bank/reklama.html', {})):
    if 'login' in request.session:
        login = request.session['login']
        return render(request, 'bank/index.html', {'login': login, 'main': main})
    else:
        return HttpResponseRedirect('/login/')

def rachunki(request):
    if 'login' in request.session:
        rachunki = Klient(Klient.get_klient_by_login(request.session['login'])).get_rachunki()
        main = render_to_string('bank/rachunki.html', {'rachunki': rachunki})
        return index(request, main)
    else:
        return HttpResponseRedirect('/login/')

def rachunek(request, numer):
    if 'login' in request.session:
        klient = Klient(Klient.get_klient_by_login(request.session['login']))
        rachunek_tuple = Rachunek.get_rachunek_by_numer(numer)
        if rachunek_tuple:
            rachunek = Rachunek(rachunek_tuple)
            if klient.id == rachunek.klient.id:
                info = ''
                if request.method == 'POST':
                    kwota = request.POST['kwota']
                    operacja = request.POST['operacja']
                    if  Operacja.operacja(rachunek, operacja, kwota):
                        info = 'Operacja zakonczona sukcesem'
                    else:
                        return index(request, 'Nie mozna wykonac zadanej operacji')
                return render(request, 'bank/rachunek.html', {'rachunek': rachunek, 'login': klient.login, 'info': info})
            else:
                return index(request, 'Brak uprawnien')
        else:
            return index(request, 'Rachunek nie istnieje')
    else:
        return HttpResponseRedirect('/login/')

def historia(request, numer):
    if 'login' in request.session:
        klient = Klient(Klient.get_klient_by_login(request.session['login']))
        rachunek_tuple = Rachunek.get_rachunek_by_numer(numer)
        if rachunek_tuple:
            rachunek = Rachunek(rachunek_tuple)
            if klient.id == rachunek.klient.id:
                operacje_wykonane = rachunek.get_history()
                main = render_to_string('bank/historia.html', {'operacje_wykonane': operacje_wykonane})
                return index(request, main)
            else:
                return index(request, 'Brak uprawnien')
        else:
            return index(request, 'Rachunek nie istnieje')
    else:
        return HttpResponseRedirect('/login/')

def zamknij(request, numer):
    if 'login' in request.session:
        klient = Klient(Klient.get_klient_by_login(request.session['login']))
        rachunek_tuple = Rachunek.get_rachunek_by_numer(numer)
        if rachunek_tuple:
            rachunek = Rachunek(rachunek_tuple)
            if klient.id == rachunek.klient.id:
                if rachunek.close():
                    return index(request, 'Rachunek zostal zamkniety')
                else:
                    return index(request, 'Nie mozna wykonac zadanej operacji')
            else:
                return index(request, 'Brak uprawnien')
        else:
            return index(request, 'Rachunek nie istnieje')
    else:
        return HttpResponseRedirect('/login/')

def otworz(request):
    if 'login' in request.session:
        klient = Klient(Klient.get_klient_by_login(request.session['login']))
        all_rodzaj = []
        for rodzaj_tuple in Rodzaj.get_all_rodzaj():
            all_rodzaj.append(Rodzaj(rodzaj_tuple))
        info = ''
        if request.method == 'POST':
            numer = request.POST['numer']
            if Rachunek.check_free(numer):
                rodzaj = request.POST['rodzaj']
                if Rachunek.otworz_rachunek(klient.id, rodzaj, numer):
                    return index(request, 'Rachunek zostal otwarty')
                else:
                    return index(request, 'Nie mozna wykonac zadanej operacji')
            else:
                info = 'Podany numer rachunku jest zajety, wybierz inny'
        return render(request, 'bank/otworz.html', {'all_rodzaj': tuple(all_rodzaj), 'info': info, 'login': klient.login})
    else:
        return HttpResponseRedirect('/login/')

def kolejny_dzien(request):
    if 'login' in request.session:
        Rachunek.next_day()
        if Rachunek.interest():
            return index(request, 'Mamy kolejny piekny dzien. Opcja prezentujaca naliczanie odsetek')
        else:
            return index(request, 'Nie mozna wykonac zadanej operacji')
    else:
        return HttpResponseRedirect('/login/')

def rodzaj(request, id):
    if 'login' in request.session:
        rodzaj_tuple = Rodzaj.get_rodzaj_by_id(id)
        if rodzaj_tuple:
            rodzaj = Rodzaj(rodzaj_tuple)
            return index(request, 'Konto: ' + rodzaj.nazwa + ', oprocentowanie wynosi ' + str(rodzaj.odsetki * 100) + '% naliczane co ' + str(rodzaj.co_ile_naliczane) + ' dni')
        else:
            return index(request, 'Rodzaj konta nie istnieje')
    else:
        return HttpResponseRedirect('/login/')

def oferta(request):
        all_rodzaj = []
        for rodzaj_tuple in Rodzaj.get_all_rodzaj():
            all_rodzaj.append(Rodzaj(rodzaj_tuple))
        if 'login' in request.session:
            login = request.session['login']
            return render(request, 'bank/oferta.html', {'all_rodzaj': tuple(all_rodzaj), 'login': login})
        else:
            return render(request, 'bank/oferta.html', {'all_rodzaj': tuple(all_rodzaj)})

def rejestracja(request):
    if 'login' in request.session:
        return index(request, 'Jestes zalogowany')
    else:
        if request.method == 'POST':
            imie = request.POST['imie']
            nazwisko = request.POST['nazwisko']
            login = request.POST['login']
            haslo = request.POST['haslo']
            if Klient.get_klient_by_login(login):
                return render(request, 'bank/rejestracja.html', {'info': 'Podany login jest zajety, wybierz inny'})
            else:
                if Klient((None, imie, nazwisko, login, haslo)).registration():
                    return HttpResponseRedirect('/login/')
                else:
                    return render(request, 'bank/rejestracja.html', {'info': 'Nie mozna wykonac zadanej operacji'})
        else:
            return render(request, 'bank/rejestracja.html', {})

bank/templates/bank/historia.html
<table class="wyniki">
    <tr>
        <th> DATA </th>
        <th> OPERACJA </th>
        <th> ZMIANA </th>
    </tr>
    {% for operacja_wykonana in operacje_wykonane %}
        <tr>
            <td> {{ operacja_wykonana.data }} </a> </td>
            <td> {{ operacja_wykonana.operacja.nazwa }} </td>
            <td> {{ operacja_wykonana.zmiana }} </td>
        </tr>
    {% endfor %}
</table>

bank/templates/bank/login.html
{% load staticfiles %}
<html>
    <head>
        <link rel="stylesheet" href="{% static 'bank/css/bank.css' %}">
    </head>
    <header>
        <h1> BANK </h1>
    </header>
    <nav>
        <table>
            <tr>
                <th> MENU </th>
            </tr>
            <tr>
                <td> <a href="{% url 'bank:index' %}"> Start </a> </td>
            </tr>
            <tr>
                <td> <a href="{% url 'bank:rachunki' %}"> Rachunki </a> </td>
            </tr>
            <tr>
                <td> <a href="{% url 'bank:otworz' %}"> Otworz Rachunek </a> </td>
            </tr>
            <tr>
                <td> <a href="{% url 'bank:oferta' %}"> Oferta </a> </td>
            </tr>
            <tr>
                <td> <a href="{% url 'bank:kolejny_dzien' %}"> Kolejny Dzien </a> </td>
            </tr>
        </table>
    </nav>
    <aside>
        <table>
            <tr>
                <th> UZYTKOWNIK </th>
            </tr>
            <tr>
                <td> <a href="{% url 'bank:rejestracja' %}"> Rejestracja </a> </td>
            </tr>
        </table>
    </aside>
    <div id="main"> <!-- <main> nie jest obsługiwany przez Internet Explorer, nawet wersję 11 -->
        <p>
            <form action="{% url 'bank:login' %}" method="post">
                {% csrf_token %}
                <table>
                    <tr>
                        <td> <label for="login"> Login: </label> </td>
                        <td class="rejestracja"> <input id="login" type="text" required="required" name="login"> </td>
                    </tr>
                    <tr>
                        <td> <label for="haslo"> Haslo: </label> </td>
                        <td class="rejestracja"> <input id="haslo" type="text" required="required" name="haslo"> </td>
                    </tr>
                    <tr>
                        <td> </td>
                        <td class="rejestracja"> <input type="submit" value="OK"> </td>
                    </tr>
                </table>
            </form>
        </p>
        <p>
            {{ info }}
        </p>
    </div>
    <footer>
        Mateusz Zielinski
    </footer>
</html>

bank/templates/bank/oferta.html
{% load staticfiles %}
<html>
    <head>
        <link rel="stylesheet" href="{% static 'bank/css/bank.css' %}">
    </head>
    <header>
        <h1> BANK </h1>
    </header>
    <nav>
        <table>
            <tr>
                <th> MENU </th>
            </tr>
            <tr>
                <td> <a href="{% url 'bank:index' %}"> Start </a> </td>
            </tr>
            <tr>
                <td> <a href="{% url 'bank:rachunki' %}"> Rachunki </a> </td>
            </tr>
            <tr>
                <td> <a href="{% url 'bank:otworz' %}"> Otworz Rachunek </a> </td>
            </tr>
            <tr>
                <td> <a href="{% url 'bank:oferta' %}"> Oferta </a> </td>
            </tr>
            <tr>
                <td> <a href="{% url 'bank:kolejny_dzien' %}"> Kolejny Dzien </a> </td>
            </tr>
        </table>
    </nav>
    <aside>
        <table>
            <tr>
                <th> UZYTKOWNIK </th>
            </tr>
            {% if login %}
                <tr>
                    <td> Jestes: {{ login }} </td>
                </tr>
                <tr>
                    <td> <a href="{% url 'bank:logout' %}"> Logout </a> </td>
                </tr>
            {% else %}
                 <tr>
                    <td> <a href="{% url 'bank:login' %}"> Login </a> </td>
                </tr>
                <tr>
                    <td> <a href="{% url 'bank:rejestracja' %}"> Rejestracja </a> </td>
                </tr>
            {% endif %}
        </table>
    </aside>
    <div id="main"> <!-- <main> nie jest obsługiwany przez Internet Explorer, nawet wersję 11 -->    
        <table>
            <tr>
                <th> OFERTA KONT </th>
            </tr>
            {% for rodzaj in all_rodzaj %}
                <tr>
                    <td> <a href="{% url 'bank:rodzaj' rodzaj.id %}"> {{ rodzaj.nazwa }} </a> </td>
                </tr>
            {% endfor %}
        </table> 
    </div>
    <footer>
        Mateusz Zielinski
    </footer>
</html>

bank/templates/bank/rachunek.html
{% load staticfiles %}
<html>
    <head>
        <link rel="stylesheet" href="{% static 'bank/css/bank.css' %}">
    </head>
    <header>
        <h1> BANK </h1>
    </header>
    <nav>
        <table>
            <tr>
                <th> MENU </th>
            </tr>
            <tr>
                <td> <a href="{% url 'bank:index' %}"> Start </a> </td>
            </tr>
            <tr>
                <td> <a href="{% url 'bank:rachunki' %}"> Rachunki </a> </td>
            </tr>
            <tr>
                <td> <a href="{% url 'bank:otworz' %}"> Otworz Rachunek </a> </td>
            </tr>
            <tr>
                <td> <a href="{% url 'bank:oferta' %}"> Oferta </a> </td>
            </tr>
            <tr>
                <td> <a href="{% url 'bank:kolejny_dzien' %}"> Kolejny Dzien </a> </td>
            </tr>
        </table>
    </nav>
    <aside>
        <table>
            <tr>
                <th> UZYTKOWNIK </th>
            </tr>
            <tr>
                <td> Jestes: {{ login }} </td>
            </tr>
            <tr>
                <td> <a href="{% url 'bank:logout' %}"> Logout </a> </td>
            </tr>
        </table>
    </aside>
    <div id="main"> <!-- <main> nie jest obsługiwany przez Internet Explorer, nawet wersję 11 -->
        <table class="wyniki">
            <tr>
                <th> NUMER </th>
                <th> SALDO </th>
                <th> RODZAJ </th>
            </tr>
            <tr>
                <td> {{ rachunek.numer }} </td>
                <td> {{ rachunek.saldo }} </td>
                <td> {{ rachunek.rodzaj.nazwa }} </td>
            </tr>
        </table>
        <p>
            <form action="{% url 'bank:rachunek' rachunek.numer %}" method="post">
                {% csrf_token %}
                <label for="login"> Kwota: </label>
                <input id="kwota" type="number" step="0.01" min="1" max="2000000000" required="required" name="kwota">
                <select id="operacja" name="operacja">
                    <option value="wplata"> Wplata </option>
                    <option value="wyplata"> Wyplata </option>
                </select>
                <input type="submit" value="OK">
            </form>
        </p>
        <p>
            <a href="{% url 'bank:historia' rachunek.numer %}"> Historia </a>
        </p>
        <p>
            <a href="{% url 'bank:zamknij' rachunek.numer %}"> Zakmnij </a>
        </p>
        <p>
            <h2> {{ info }} </h2>
        </p>
    </div>
    <footer>
        Mateusz Zielinski
    </footer>
</html>

bank/templates/bank/rachunki.html
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'bank/css/bank.css' %}">

<table class="wyniki">
    <tr>
        <th> NUMER </th>
        <th> SALDO </th>
        <th> RODZAJ </th>
    </tr>
    {% for rachunek in rachunki %}
        <tr>
            <td> <a href="{% url 'bank:rachunek' rachunek.numer %}"> {{ rachunek.numer }} </a> </td>
            <td> {{ rachunek.saldo }} </td>
            <td> <a href="{% url 'bank:rodzaj' rachunek.rodzaj.id %}"> {{ rachunek.rodzaj.nazwa }} </a> </td>
        </tr>
    {% endfor %}
</table>

bank/templates/bank/rejestracja.html
{% load staticfiles %}
<html>
    <head>
        <link rel="stylesheet" href="{% static 'bank/css/bank.css' %}">
    </head>
    <header>
        <h1> BANK </h1>
    </header>
    <nav>
        <table>
            <tr>
                <th> MENU </th>
            </tr>
            <tr>
                <td> <a href="{% url 'bank:index' %}"> Start </a> </td>
            </tr>
            <tr>
                <td> <a href="{% url 'bank:rachunki' %}"> Rachunki </a> </td>
            </tr>
            <tr>
                <td> <a href="{% url 'bank:otworz' %}"> Otworz Rachunek </a> </td>
            </tr>
            <tr>
                <td> <a href="{% url 'bank:oferta' %}"> Oferta </a> </td>
            </tr>
            <tr>
                <td> <a href="{% url 'bank:kolejny_dzien' %}"> Kolejny Dzien </a> </td>
            </tr>
        </table>
    </nav>
    <aside>
        <table>
            <tr>
                <th> UZYTKOWNIK </th>
            </tr>
            <tr>
                <td> <a href="{% url 'bank:login' %}"> Login </a> </td>
            </tr>
        </table>
    </aside>
    <div id="main"> <!-- <main> nie jest obsługiwany przez Internet Explorer, nawet wersję 11 -->
        <p>
        <form action="{% url 'bank:rejestracja' %}" method="post">
            {% csrf_token %}
            <table>
                <tr>
                    <td> <label for="imie"> Imie: </label> </td>
                    <td class="rejestracja"> <input id="imie" type="text" required="required" name="imie"> </td>
                </tr>
                <tr>
                    <td> <label for="nazwisko"> Nazwisko: </label> </td>
                    <td class="rejestracja"> <input id="nazwisko" type="text" required="required" name="nazwisko"> </td>
                </tr>
                <tr>
                    <td> <label for="login"> Login: </label> </td>
                    <td class="rejestracja"> <input id="login" type="text" required="required" name="login"> </td>
                </tr>
                <tr>
                    <td> <label for="haslo"> Haslo: </label> </td>
                    <td class="rejestracja"> <input id="haslo" type="text" required="required" name="haslo"> </td>
                </tr>
                <tr>
                    <td></td>
                    <td class="rejestracja"> <input type="submit" value="OK"> </td>
                </tr>
            </table>
        </form>
        </p>
        <p>
            {{ info }}
        </p>
    </div>
    <footer>
        Mateusz Zielinski
    </footer>
</html>

bank/templates/bank/reklama.html
<p> Najlepszy bank! </p>
<p> Najlesze uslugi! </p>
<p> Wysoko oprocentowane konta! </p>
<p> Dobre piwo! </p>